# Generated by Django 3.1.2 on 2020-10-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adhar_card',
            new_name='aadhar_card',
        ),
    ]
