# Generated by Django 3.1.2 on 2020-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='type',
            new_name='type_c',
        ),
    ]
