# Generated by Django 3.1.2 on 2020-11-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_auto_20201121_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.TextField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
