# Generated by Django 3.1.2 on 2020-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='wearhouse',
            field=models.CharField(choices=[('BALEWADI', 'Balewadi'), ('SHIVAJINAGAR', 'Shivajinagar')], default='BALEWADI', max_length=15),
        ),
    ]
